export interface User {
  id: string;
  email: string;
  name: string | null;
  role: 'user' | 'admin';
}

export interface Category {
  id: string;
  slug: string;
  name: string;
  description?: string | null;
  image?: string | null;
}

export interface ProductCard {
  id: string;
  slug: string;
  name: string;
  shortDescription: string | null;
  type: 'key' | 'file' | 'subscription' | 'script';
  priceCents: number;
  compareAtCents: number | null;
  image: string | null;
  badge: string | null;
  rating: number;
  category: { id: string; slug: string; name: string } | null;
  inStock: boolean;
}

export interface ProductDetail extends ProductCard {
  description?: string | null;
  keywords?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  gallery: string[];
  durationDays?: number | null;
  stock: number;
  files: { id: string; label: string; sizeBytes: number | null }[];
  reviews: Review[];
}

export interface Review {
  id: string;
  productId: string;
  userId: string | null;
  authorName: string;
  rating: number;
  title: string | null;
  body: string | null;
  isApproved: boolean;
  createdAt: number | string | Date;
}

export interface OrderItem {
  id: string;
  productSlug: string;
  productName: string;
  productType: string;
  unitPriceCents: number;
  quantity: number;
  deliveredKey: string | null;
}

export interface OrderDetail {
  id: string;
  orderNumber: string;
  status:
    | 'pending'
    | 'awaiting_payment'
    | 'partial'
    | 'paid'
    | 'fulfilled'
    | 'expired'
    | 'cancelled'
    | 'refunded';
  currency: string;
  subtotalCents: number;
  discountCents: number;
  totalCents: number;
  crypto: {
    /** Currency code, e.g. 'btc' / 'usdt@trx'. */
    currency: string | null;
    /** Deposit address generated by Apirone. */
    address: string | null;
    /** Expected amount in minor units, BigInt-safe string. */
    amountMinor: string | null;
    /** Total received minor units (BigInt-safe string). */
    received: string;
    /** Highest confirmation count seen. */
    confirmations: number;
    /** Last seen tx hash. */
    txHash: string | null;
    /** Locked-in fiat-per-crypto rate at order time (string for precision). */
    rate: string | null;
  };
  expiresAt: string | null;
  fulfilledAt: string | null;
  createdAt: string;
  items: OrderItem[];
}
